### ISSUE TITLE
AMP usage

### ISSUE THREAD

**Issue by tarepan** [quickvc/QuickVC-VoiceConversion#11]
## Summary
QuickVC have AMP config.  
When I use it, raise a error and cannot train.  
Did you use AMP for training?  

## Current Status
QuickVC have AMP (automatic mixed-presicion) training flag.  
https://github.com/quickvc/QuickVC-VoiceConversion/blob/277118de9c81d1689e16be8a43408eda4223553d/configs/quickvc.json#L11

This will speed up training in certain hardware, including RTX3090, which was used for the paper.  
>  Our models are trained on a single NVIDIA 3090 GPU

When I try AMP with `"fp16_run": true` config, below error was raised.  
```
RuntimeError: cuFFT only supports dimensions whose sizes are powers of two when computing in half precision, but got a signal size of[1280]
```

## Question
- Did you use AMP training for the paper?
- Does QuickVC support AMP training?

If you didn't use AMP, I have additional question for future modification of QuickVC:

- Have you ever changed STFT's n_fft?
- Do you think 'changing n_fft' have big effect on the result? (I want to change it for AMP)

**Comment by guoyingying432** [comment]
Sorry, I didn't use AMP training for the paper. And I think 'changing n_fft' don't have big effect on the result.

**Comment by tarepan** [comment]
Thanks for the answer!

**Comment by skol101** [comment]
@tarepan I've checked your fork to see how AMP quickens learning. Have you tried this https://github.com/ELS-RD/kernl  to accelerate even more?
