### ISSUE TITLE
Why does the system use an any-to-many configuration over a any-to-any one?

### ISSUE THREAD

**Issue by Shayne-Ada** [quickvc/QuickVC-VoiceConversion#13]
Hello, I am wondering why this system employs a any-to-many configuration instead of any-to-any. Moreover, during my tests, I've observed that the converted speech often converges to a specific voice in the training set.What's the reason behind this? I also noticed that the speaker encoder does not employ one-hot vectors. Is this issue attributable to the limited variety of speakers in the VCTK dataset, or does the VITS synthesis of high-quality speech compromise the diversity of speaker types?

**Comment by ConsistencyVC** [comment]
Because the model is a small model, only big model with big dataset, like Diffusion, VALL-E, can achieve real any-to-any. So if you want to achieve high diversity of speaker types, QuickVC is not a good choice.
