### ISSUE TITLE
Deviation from paper: speaker encoder LSTM layer

### ISSUE THREAD

**Issue by tarepan** [quickvc/QuickVC-VoiceConversion#14]
## Summary
The paper said that LSTM is *one layer*.  
The implementation use **3-layer** LSTM.  
Which is correct?  

## Current status
The paper said that speaker encoder sub-model consists of *one layer of LSTM structure*.  

> The network structure of the speaker encoder contains one layer of LSTM structure and one layer of fully connected layers

But, `SpeakerEncoder` implementation use 3-layer LSTM module.  

https://github.com/quickvc/QuickVC-VoiceConversion/blob/277118de9c81d1689e16be8a43408eda4223553d/models.py#L601-L604  

So, there seems to be a deviation from the paper in implementation.  

## Question
- For result/demo of the paper, how many LSTM layers are used?
- Is this a deviation or just interpretation of the word ***LSTM structure***? (`one layer of LSTM structure` == `one block of 3-layer LSTM module`?)

**Comment by quickvc** [comment]
Sorry for the inconvenience.

The open-sourced code is the correct answer.
So  one layer of LSTM structure == one block of 3-layer LSTM module

By the way, after about four months, from my current point of view, there is a lot of disadvantage to this work Q_Q

**Comment by tarepan** [comment]
Thanks for clear answer!  

Even if there are some disadvantages, open-sourced QuickVC has contributed a lot to the community!  
I am looking forward to improved works of you and your teams in future😉
