### ISSUE TITLE
use_sr isn't used in the actual code

### ISSUE THREAD

**Issue by skol101** [quickvc/QuickVC-VoiceConversion#15]
Looks like, unlike FreeVC https://github.com/OlaWod/FreeVC/blob/81c169cdbfc97ff07ee2f501e9b88d543fc46126/data_utils.py#L72C9-L72C9 your code doesn't explicitly use this param, in fact it doens't use SR at all?

https://github.com/quickvc/QuickVC-VoiceConversion/blob/277118de9c81d1689e16be8a43408eda4223553d/data_utils_new_new.py#L70

**Comment by guoyingying432** [comment]
For convenience when writing code, I designed sr to be manual.  If you want to use sr data augmentation, just remove the comment.

**Comment by quickvc** [comment]
I'm sorry for the inconvenience, this is a bug in the uploaded code version,  in order to use sr, just change [that line](https://github.com/quickvc/QuickVC-VoiceConversion/blob/277118de9c81d1689e16be8a43408eda4223553d/data_utils_new_new.py#L70) to 
`i = random.randint(68,92)
c_filename = filename.replace(".wav", f"_{i}.npy")`

I just changed the readme, thank you for your reminder.

**Comment by skol101** [comment]
https://github.com/OlaWod/FreeVC/blob/main/preprocess_sr.py creates .pt files (not .npy).

**Comment by quickvc** [comment]
This because the difference between the  Hubert-soft and the wavlm. The output of Hubert-soft is npy, but wavlm is pt

**Comment by skol101** [comment]
I see, so that means preprocess_sr must be also updated to Hubert-soft and re-run for the dataset.

**Comment by quickvc** [comment]
Yes

**Comment by skol101** [comment]
Training time goes significantly up with SR augmentation...which is probably expected.

**Comment by quickvc** [comment]
Actually, the most terrible part of SR augmentation is the data storage space... actually quickvc is already four months old research. Now I found a better content feature compared to Hubert-soft, the new content feature doesn't need augmentation and can achieve cross-lingual voice conversion. If you are interested, welcome to see [consistencyvc](https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion)

**Comment by skol101** [comment]
But you should also change this part in readme
``Spectrogram resize data augumentation, please refer to [FreeVC](https://github.com/OlaWod/FreeVC).

Because FreeVCś SR augumentation isn´t used at all here.

**Comment by Cheneng** [comment]
In my experiments on sovits by using whisper ppg, there will more timbre leakage on vc comparing to contentvec or hubert. Have you try on contentvec? In Consistencyvc, It seems that speaker consistency loss solves this problem rather than content feature, am I right?
