### ISSUE TITLE
Typo in paper and repository

### ISSUE THREAD

**Issue by tarepan** [quickvc/QuickVC-VoiceConversion#3]
## Summary
There are typo or inconsistency about "**any-to-many**" in the paper and repository.  
For example, title is ***Many-to-any*** but introduction says that porpose is **any-to-many**.  
Is this typo?  

## Current Status
There are some inconsistency in the paper.  

In introduction in the paper, it says **any-to-many**.  
> In this article, we aim at **any-to-many** voice conversion

QuickVC use speaker-independent HuBERT, so **any-to** is understandable.  

But title of the paper says ***many-to-any***.  
> QuickVC: ***Many-to-any*** Voice Conversion Using Inverse Short-time Fourier Transform for Faster Conversion

It is inconsistent with introduction's claim.  

## Inconsistency List
I listed up inconsistency or typo.

- title
  - > QuickVC: ***Many-to-any*** Voice Conversion Using Inverse Short-time Fourier Transform for Faster Conversion
- introduction
  - > we aim at **any-to-many** voice conversion
  - > HuBERT-Soft to achieve high-quality ***many-to-any*** speech conversion.
- method
  - > speaker embedding g, to achieve ***many-to-any*** VC.
- Experiment
  - > to test the ability of the model in the **any-to-many** VC scenario.
- repository
  - about
    - > QuickVC: ***Many-to-any***
  - README
    - > of my paper: QuickVC: ***Many-to-any***
- Demo page
  - > QuickVC: ***Many-To-Any***

## Question
Are they just typo, or intentionally distinguished?  

## Notes
Thanks for your great paper, I am so impressed by the results.  
I am really looking forward to code release!

**Comment by quickvc** [comment]
Sorry! Thank you for you suggestion. Any to many is the true condition, I will revise the preprint paper as soon as possible. Thank you very much!

**Comment by tarepan** [comment]
Thank you for 'quick' response.  
I checked all typos and all problems are fixed, great!
