### ISSUE TITLE
Experiment or sample in cross-lingual setting

### ISSUE THREAD

**Issue by seastar105** [quickvc/QuickVC-VoiceConversion#4]
as soft-vc showed quite good performance in crosslingual setting, could you provide some sample in cross-lingual setting? e.g) french -> english, japanese -> english

**Comment by quickvc** [comment]
I tested the soft-vc model by[ Japanese dataset](https://sites.google.com/site/shinnosuketakamichi/research-topics/jvs_corpus), the source speech is [this](https://drive.google.com/file/d/1mtto8or2kDD4iYjPQD2VLkcZtEU--C2G/view?usp=share_link), but the [result](https://drive.google.com/file/d/1tdpH0jrR5JnsFC1IK_gaXkK1eMUNoiMI/view?usp=share_link) doesn't good. It is similar to the target speaker, and there is no noise. But according to my Japanese friends, it is just like a foreigner speaking Japanese. So I think if you want to train a content extractor for Japanese, you need to train a new Hubert by Japanese, it is a hard job.
Actually, I'm not Japanese, so I am sorry that I'm not sure how to explain the disadvantage of this result.

**Comment by seastar105** [comment]
@quickvc That's actually what i got from asian-western cross-lingual setting with soft-vc. I can get your point. thanks!

**Comment by quickvc** [comment]
To achieve cross-lingual voice conversion, we can get help from the cross-lingual voice conversion model Whisper, this is a new research achieved high-quality cross-lingual voice conversion:
https://github.com/ConsistencyVC/ConsistencyVC-voive-conversion
