### ISSUE TITLE
Is there any pretrained model that can provided for us to test?

### ISSUE THREAD

**Issue by hunter2009pf** [quickvc/QuickVC-VoiceConversion#9]
I want to have a trial on quickvc but I don't have large-enough dataset to train the model. Can author provide one so that we can have a trial on quickVC inference right now?

**Comment by quickvc** [comment]
Please check readme, there is pretrained model.

**Comment by hunter2009pf** [comment]
I found it.
![image](https://github.com/quickvc/QuickVC-VoiceConversion/assets/32154029/2e0235e7-b250-4106-8703-2a491168b73a)
